wandb_version: 1

ICA_training_size:
  desc: null
  value: 1000
PCA_training_size:
  desc: null
  value: 5000
VAE_loss:
  desc: null
  value: betaB
_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.23
      8:
      - 5
classifier_hidden_size:
  desc: null
  value: 512
latent_size:
  desc: null
  value: 10
sample_size:
  desc: null
  value: 300
